import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        canvas: 'var(--canvas)',
        bg: 'var(--bg)',
        'surface-1': 'var(--surface-1)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        'surface-4': 'var(--surface-4)',
        'surface-hover': 'var(--surface-hover)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        'grid-dot': 'var(--grid-dot)',
        text: 'var(--text)',
        'text-muted': 'var(--text-muted)',
        'text-faint': 'var(--text-faint)',
        primary: {
          DEFAULT: 'var(--primary)',
          hover: 'var(--primary-hover)',
          fg: 'var(--primary-fg)',
          soft: 'var(--primary-soft)',
          ring: 'var(--primary-ring)',
        },
        success: {
          DEFAULT: 'var(--success)',
          soft: 'var(--success-soft)',
        },
        warning: {
          DEFAULT: 'var(--warning)',
          soft: 'var(--warning-soft)',
        },
        danger: {
          DEFAULT: 'var(--danger)',
          soft: 'var(--danger-soft)',
        },
        accent: 'var(--accent)',
        kind: {
          class: 'var(--kind-class)',
          abstract: 'var(--kind-abstract)',
          interface: 'var(--kind-interface)',
          enum: 'var(--kind-enum)',
          record: 'var(--kind-record)',
        },
        ink: {
          cyan: 'var(--ink-cyan)',
          red: 'var(--ink-red)',
          amber: 'var(--ink-amber)',
          purple: 'var(--ink-purple)',
          white: 'var(--ink-white)',
        },
        sticky: {
          white: 'var(--sticky-white)',
          red: 'var(--sticky-red)',
          orange: 'var(--sticky-orange)',
          green: 'var(--sticky-green)',
          teal: 'var(--sticky-teal)',
          purple: 'var(--sticky-purple)',
          pink: 'var(--sticky-pink)',
          default: 'var(--sticky-default)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      spacing: {
        '1': 'var(--sp-1)',
        '2': 'var(--sp-2)',
        '3': 'var(--sp-3)',
        '4': 'var(--sp-4)',
        '5': 'var(--sp-5)',
        '6': 'var(--sp-6)',
        '8': 'var(--sp-8)',
        '10': 'var(--sp-10)',
        header: 'var(--header-h)',
        palette: 'var(--palette-w)',
        panel: 'var(--panel-w)',
        'panel-lg': 'var(--panel-w-lg)',
        tabbar: 'var(--tabbar-h)',
      },
      borderRadius: {
        sm: 'var(--r-sm)',
        md: 'var(--r-md)',
        lg: 'var(--r-lg)',
        xl: 'var(--r-xl)',
        full: 'var(--r-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      transitionTimingFunction: {
        'ease-out': 'var(--ease-out)',
      },
      transitionDuration: {
        fast: 'var(--dur-fast)',
        base: 'var(--dur-base)',
        modal: 'var(--dur-modal)',
      },
    },
  },
  plugins: [],
} satisfies Config;
